### ISSUE TITLE
akka-quartz-scheduler for Akka 2.3 and Scala 2.10

### ISSUE THREAD

**Issue by pollycchang** [enragedginger/akka-quartz-scheduler#14]
We have an existing project that is using Scala 2.10, and I would like to use Akka 2.3 and also akka-quartz-scheduler. I see that akka-quartz-scheduler for Akka 2.3 is only compiled for Scala 2.11. Since Akka 2.3 also supports Scala 2.10, can you please publish a version for Scala 2.10? Thanks!

**Comment by enragedginger** [comment]
Sorry it took me awhile to get around to this, but I've just published a build for Scala 2.10 and Akka 2.3 to Maven Central.

**Comment by pollycchang** [comment]
Thanks so much!!

**Comment by pollycchang** [comment]
btw, the README says to reference this artifact as:
// For Akka 2.3.x and Scala 2.10.4
libraryDependencies += "com.typesafe.akka" % "akka-quartz-scheduler_2.10" % "1.4.0-akka-2.3.x"

However, this did not resolve for me. I had to change the groupid to "com.enragedginger". Then the artifact resolved. Thanks again!
